### ISSUE TITLE
Widget closes when leaving first settings screen

### ISSUE THREAD

**Issue by CorentinLavergne** [mvmike/min-cal-widget#182] opened 2023-08-11 16:15 UTC
A frustrating issue, when you close the setting after putting the widget on the board, the widget disappear (you can see it during a frame and that's all)

**Comment by mvmike** [comment] 2023-08-11 19:05
Hi @CorentinLavergne, would you mind providing more information so I can reproduce this? app version, device, android version, launcher...

**Comment by jimktrains** [comment] 2023-08-13 17:08
Pixel 4a, Android 13, Lawnchait launcher v2

**Comment by mvmike** [comment] 2023-08-14 11:31
Couldn't reproduce in the emulator using a pixel 4a in android 13, neither in the [latest alpha](https://github.com/LawnchairLauncher/lawnchair/releases/tag/v12.1.0-alpha.4) from lawnchair nor the [latest debug apk build](https://github.com/LawnchairLauncher/lawnchair/actions/runs/5852486541).

![Screenshot at 2023-08-14 13-27-37](https://github.com/mvmike/min-cal-widget/assets/20406251/69ce4443-ab99-4d48-82e6-4d666fa4045d)

Could you confirm that Lawnchair has permissions to create widgets? A logcat would also be really helpful.

PS: @mvdan IIRC you had that same device, would you mind trying to reproduce the issue too? 🙏🏻

**Comment by jimktrains** [comment] 2023-08-15 00:46
Yes, I can confirm it can create widgets as it has other widgets on it. I can see if I can get a logcat.

The Google Calendar widget was behaving the same way.  It looks like Lawnchair2 hasn't been updated in a few years, so I switched over to Nova, and the widget work there.

**Comment by mvmike** [comment] 2023-08-17 20:43
Thanks for the info, @jimktrains, could finally reproduce the issue. Even though it is related on how Android 13 sends the closing activity intent (from the configuration screen) to the launcher and those launchers that are targeting newest android versions are not experiencing problems here since it works out of the box, could find a workaround and implemented it under https://github.com/mvmike/min-cal-widget/commit/0de32f0f09b8f9b30741f9b63f3dab3d28a45092.

This should also cover other old launchers being used in newer android versions.

**Closed by mvmike** 2023-08-17 20:43 UTC
Labels: bug
