### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by 532910** [mvmike/min-cal-widget#50] opened 2020-06-11 15:47 UTC
I just noted that `8` (Mon) was marked as the current day. I've removed the widget and re-added it. Now it shows `11`. Sure it happened after the last update that happened on 08 Jun 2020.

**Comment by mvmike** [comment] 2020-06-12 15:58
Tried to reproduce without success in a couple of devices.

Unfortunately, this is something hard to handle on the widget side, it's the very same case as in #41

**Comment by 532910** [comment] 2020-06-12 16:01
In fact it's completely broken for me, as it doesn't updates at all and shows `11` right now. Please reopen. I'm sure it happened after the last update min-cal-widget, I've not updated system for several monthes.

**Comment by mvmike** [comment] 2020-06-12 16:07
Tried in two phones, one with android 9 and another with 10, both dirty application upgrades (without clearing cache or data) and could not reproduce it.

In any case, as said, widget update depends completely on an ID that's assigned by the OS, there is no way from our app to force it's redraw if not being called by the OS. Do you mind deleting the widget, cleaning data and cache of the app, and re-add it?

If it still persists, we can explore other options such as generating a debug version with more logging or sharing your OS details and see if i can get a virtual machine that's more similar to your setup

**Comment by 532910** [comment] 2020-06-12 16:15
Looks like it works fine on another lineageos 17.1 (android 10).
But on mine lineageos 16  +microgaps (android 9) it doesn't update.
I have [24h Clock Widget](https://f-droid.org/packages/info.staticfree.android.twentyfourhour/) on the same screen and it ticks every minute.

Both widgets has the same battery usage settings:
`App can use battery in background` and `Optimizing battery use`

> Do you mind deleting the widget, cleaning data and cache of the app, and re-add it?

Let's start with phone reboot.

**Comment by 532910** [comment] 2020-06-19 10:02
Hm, looks like it was some phone issue, as it works fine now and I can't reproduce this.

**Comment by 532910** [comment] 2020-10-04 11:47
I ran again into this issue. Looks it happens on update.

**Comment by mvmike** [comment] 2020-10-04 18:01
On update of the widget?

**Comment by 532910** [comment] 2020-10-04 21:28
Yep, it happened after the update, Sep 30. This is the date F-Droid shows it was updated and the date the widget stalled on.

**Comment by 532910** [comment] 2021-03-16 07:52
This issue is still actual and happens every app update (from fdroid).

**Comment by mvmike** [comment] 2021-05-10 12:24
Since there is no API function to check if a receiver is registered, wrapped the functionality with a try/catch and we try to re-register receivers on each update.

Should be fixed after 94ecfabf93d660e792ef91a427b4cb05be774ae6

Could you please try with the new release?

**Comment by mvmike** [comment] 2021-06-08 07:30
Answering myself, this seems to not be fixed and still fails randomly when upgrading the app. Will take another look at the docs and other open source apps to try to fix it in another way

**Comment by mvmike** [comment] 2021-07-01 15:08
took some time, but theoretically should be resolved after 591046c482db28375933ca133fefb160b67c3497

the thing is that the alarm is only set when the widget is enabled, so once [the new 2.0.2 version](https://github.com/mvmike/min-cal-widget/releases/tag/v2.0.2) is installed, the widget needs to be replaced so future upgrades will break anything

**Comment by mvmike** [comment] 2021-07-01 15:10
also, with previous versions, rebooting the phone or replacing the widget was fixing the issue too, it looks more like a misbehaviour of the `android:updatePeriodMillis` functionality, the alarm feels like a patch although everybody is using it

**Closed** 2021-07-01 15:11 UTC
Labels: bug
